export const DELETE_EXCERCISE = 'DELETE_EXCERCISE'

export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE'
export const CHANGE_SELECTION = 'CHANGE_SELECTION'

export const ADD_LINK = 'ADD_LINK'
export const ADD_SPLIT = 'ADD_SPLIT'

export const SELECT_EXCERCISES_FOR_NEW_SPLIT = 'SELECT_EXCERCISES_FOR_NEW_SPLIT'
export const SELECT_DATE_FOR_NEW_SPLIT = 'SELECT_DATE_FOR_NEW_SPLIT'
export const ADD_SET_IN_NEW_SPLIT = 'ADD_SET_IN_NEW_SPLIT'
export const DELETE_EXCERCISE_FROM_NEW_SPLIT = 'DELETE_EXCERCISE_FROM_NEW_SPLIT'
export const DELETE_EXCERCISE_FROM_SELECT = 'DELETE_EXCERCISE_FROM_SELECT'

export const OPEN_EXCERCISE_SELECT = 'OPEN_EXCERCISE_SELECT'
export const CLOSE_EXCERCISE_SELECT = 'CLOSE_EXCERCISE_SELECT'

export const ADD_RATE = 'ADD_RATE'

export const ADD = '_ADD'
export const REMOVE = '_REMOVE'

export const LOAD_SPLITS = 'LOAD_SPLITS'
export const DELETE_SPLIT = 'DELETE_SPLIT'

export const CHECK_EXCERCISE_TITLE = 'CHECK_EXCERCISE_TITLE'
export const SET_EXCERCISE_TITLE = 'SET_EXCERCISE_TITLE'
export const SET_EXCERCISE_TEXT = 'SET_EXCERCISE_TEXT'
export const ADD_EXCERCISE = 'ADD_EXCERCISE'
export const TOGGLE_NEW_EXCERCISE_FORM = 'TOGGLE_NEW_EXCERCISE_FORM'
export const ERROR = '_ERROR'

export const LOAD_EXCERCISES = 'LOAD_EXCERCISES'

export const TOGGLE_LOGIN_FORM = 'TOGGLE_LOGIN_FORM'
export const OPEN_LOGIN_FORM = 'OPEN_LOGIN_FORM'
export const CLOSE_LOGIN_FORM = 'CLOSE_LOGIN_FORM'
export const SET_LOGIN_FIELD = 'SET_LOGIN_FIELD'
export const CHECK_NAME_UNIQUE = 'CHECK_NAME_UNIQUE'
export const CHECK_EMAIL_UNIQUE = 'CHECK_EMAIL_UNIQUE'

export const ADD_USER = 'ADD_USER'
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
