export const DELETE_EXCERCISE = 'DELETE_EXCERCISE'

export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE'
export const CHANGE_SELECTION = 'CHANGE_SELECTION'

export const ADD_LINK = 'ADD_LINK'
export const ADD_SPLIT = 'ADD_SPLIT'

export const SHOW_DIARY = 'SHOW_DIARY'

export const SELECT_EXCERCISES_FOR_NEW_SPLIT = 'SELECT_EXCERCISES_FOR_NEW_SPLIT'
export const SELECT_DATE_FOR_NEW_SPLIT = 'SELECT_DATE_FOR_NEW_SPLIT'
export const ADD_SET_IN_NEW_SPLIT = 'ADD_SET_IN_NEW_SPLIT'

export const ADD = '_ADD'
export const REMOVE = '_REMOVE'
